# Generated by Django 5.2.7 on 2025-12-29 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("policies", "0004_remove_policy_city_address_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_number", models.CharField(max_length=30)),
                (
                    "burial_order",
                    models.FileField(
                        blank=True, null=True, upload_to="claims/burial_orders/"
                    ),
                ),
                (
                    "death_certificate",
                    models.FileField(
                        blank=True, null=True, upload_to="claims/death_certificates/"
                    ),
                ),
                ("claim_form", models.FileField(upload_to="claims/claim_forms/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("PAID", "Paid"),
                        ],
                        db_index=True,
                        default="REQUESTED",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "claimant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claims",
                        to="policies.policy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PendingClaimApproval",
            fields=[],
            options={
                "verbose_name": "Claim Approval",
                "verbose_name_plural": "Claim Approvals",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("claims.claim",),
        ),
        migrations.CreateModel(
            name="PendingClaimRequest",
            fields=[],
            options={
                "verbose_name": "Claim Request",
                "verbose_name_plural": "Claim Requests",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("claims.claim",),
        ),
    ]
