# Generated by Django 5.2.7 on 2025-12-30 17:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0002_claim_bank_branch_claim_bank_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
    ]
