# Generated by Django 5.2.7 on 2026-01-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0003_alter_claim_approved_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="reject_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
