# Generated by Django 5.2.7 on 2025-12-04 14:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_code",
                    models.CharField(db_index=True, max_length=6, unique=True),
                ),
                ("agent_name", models.CharField(max_length=200)),
                ("agent_surname", models.CharField(max_length=200)),
                ("branch", models.CharField(max_length=100)),
                ("date_joining", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_code",
                    models.CharField(db_index=True, max_length=10, unique=True),
                ),
                ("client_name", models.CharField(max_length=200)),
                ("client_surname", models.CharField(max_length=200)),
                ("id_number", models.CharField(max_length=12, unique=True)),
                ("dob", models.DateField()),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be 7–15 digits and may start with +",
                                regex="^\\+?\\d{7,15}$",
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Paypoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paypoint_code",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("paypoint_name", models.CharField(max_length=200)),
                ("date_joined", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_id",
                    models.CharField(db_index=True, max_length=10, unique=True),
                ),
                ("product_name", models.CharField(max_length=30)),
                ("product_code", models.CharField(max_length=4)),
                (
                    "contract_premium",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("start_date", models.DateField()),
                ("proposal_sign_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACCEPTED", "Accepted"),
                            ("ACTIVE", "Active"),
                            ("LAPSED", "Lapsed"),
                            ("NTU", "Ntu"),
                        ],
                        db_index=True,
                        default="ACCEPTED",
                        max_length=10,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("M", "Monthly"),
                            ("Q", "Quarterly"),
                            ("H", "Half Yearly"),
                            ("Y", "Yearly"),
                        ],
                        db_index=True,
                        default="M",
                        max_length=1,
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="policies",
                        to="life_management.agent",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="policies",
                        to="life_management.client",
                    ),
                ),
                (
                    "paypoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="policies",
                        to="life_management.paypoint",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PremiumReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receipt_number", models.CharField(max_length=8, unique=True)),
                (
                    "amount_received",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                (
                    "date_received",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="life_management.policy",
                    ),
                ),
            ],
        ),
    ]
