# Generated by Django 5.2.7 on 2025-12-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("life_management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="policy",
            name="status",
        ),
        migrations.AddField(
            model_name="policy",
            name="cover",
            field=models.PositiveIntegerField(
                choices=[(500, "$500"), (1000, "$1000"), (2000, "$2000")], default=1
            ),
            preserve_default=False,
        ),
    ]
