# Generated by Django 5.2.7 on 2025-12-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("life_management", "0002_remove_policy_status_policy_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="contract_premium",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
