# Generated by Django 5.2.7 on 2025-12-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("life_management", "0003_alter_policy_contract_premium"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="contract_premium",
            field=models.DecimalField(
                decimal_places=2, editable=False, max_digits=6, null=True
            ),
        ),
    ]
