# Generated by Django 5.2.7 on 2025-12-05 11:18

import django.utils.timezone
import life_management.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("life_management", "0004_alter_policy_contract_premium"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="current_month",
            field=models.DateField(
                default=django.utils.timezone.localdate, editable=False
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="duration",
            field=models.PositiveIntegerField(
                editable=False, help_text="Elapsed months since start_date", null=True
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="total_premium_due",
            field=models.DecimalField(
                decimal_places=2, editable=False, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="total_premium_received",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), editable=False, max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="premiumreceipt",
            name="total_received",
            field=models.DecimalField(
                decimal_places=2, default=1, editable=False, max_digits=10
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="policy",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("M", "Monthly"),
                    ("Q", "Quarterly"),
                    ("H", "Half-yearly"),
                    ("Y", "Yearly"),
                ],
                db_index=True,
                default="M",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="start_date",
            field=models.DateField(
                validators=[life_management.models.validate_first_day]
            ),
        ),
    ]
