# Generated by Django 5.2.7 on 2025-12-05 12:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("life_management", "0005_policy_current_month_policy_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="months_in_arrears",
            field=models.IntegerField(default=1, editable=False, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="policy",
            name="total_premium_arrears",
            field=models.DecimalField(
                decimal_places=2, default=1, editable=False, max_digits=12
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="policy",
            name="total_premium_due",
            field=models.DecimalField(
                decimal_places=2, default=1, editable=False, max_digits=12
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="premiumreceipt",
            name="total_received",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), editable=False, max_digits=10
            ),
        ),
    ]
