# Generated by Django 5.2.7 on 2025-12-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("life_management", "0006_policy_months_in_arrears_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="months_in_arrears",
            field=models.IntegerField(editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="policy",
            name="total_premium_arrears",
            field=models.DecimalField(
                decimal_places=2, editable=False, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="total_premium_due",
            field=models.DecimalField(
                decimal_places=2, editable=False, max_digits=12, null=True
            ),
        ),
    ]
