# Generated by Django 5.2.7 on 2025-12-05 13:17

import life_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("life_management", "0007_alter_policy_months_in_arrears_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="months_paid",
            field=models.IntegerField(editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="policy",
            name="policy_status",
            field=models.CharField(
                editable=False,
                max_length=200,
                null=True,
                validators=[life_management.models.validate_status],
            ),
        ),
    ]
