# Generated by Django 5.2.7 on 2025-12-05 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("life_management", "0008_policy_months_paid_policy_policy_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="policy",
            name="months_in_arrears",
        ),
        migrations.RemoveField(
            model_name="policy",
            name="months_paid",
        ),
        migrations.RemoveField(
            model_name="policy",
            name="policy_status",
        ),
    ]
