# Generated by Django 5.2.7 on 2025-12-18 15:25

import agents.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_code",
                    models.CharField(
                        db_index=True, editable=False, max_length=6, unique=True
                    ),
                ),
                ("agent_name", models.CharField(max_length=200)),
                ("agent_surname", models.CharField(max_length=200)),
                (
                    "branch",
                    models.CharField(
                        choices=[
                            ("HARARE", "Harare"),
                            ("MUTARE", "Mutare"),
                            ("KWEKWE", "Kwekwe"),
                            ("BULAWAYO", "Bulawayo"),
                            ("MASVINGO", "Masvingo"),
                            ("VICTORIA_FALLS", "Victoria Falls"),
                        ],
                        db_index=True,
                        max_length=100,
                    ),
                ),
                (
                    "date_joining",
                    models.DateField(
                        validators=[agents.validators.validate_date_joining]
                    ),
                ),
            ],
        ),
    ]
