# Generated by Django 5.2.7 on 2025-12-18 15:25

import django.db.models.deletion
import django.utils.timezone
import policies.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agents", "0001_initial"),
        ("clients", "0001_initial"),
        ("paypoints", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_id",
                    models.CharField(
                        db_index=True, editable=False, max_length=10, unique=True
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        choices=[("AFFINITY", "Affinity"), ("FUNERAL", "Funeral")],
                        max_length=30,
                    ),
                ),
                ("product_code", models.CharField(editable=False, max_length=4)),
                (
                    "proposal_sign_date",
                    models.DateField(
                        validators=[policies.validators.proposal_sign_date]
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        validators=[policies.validators.validate_first_day]
                    ),
                ),
                (
                    "current_month",
                    models.DateField(
                        default=django.utils.timezone.localdate, editable=False
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        editable=False,
                        help_text="Elapsed months since start_date",
                        null=True,
                    ),
                ),
                (
                    "total_premium_received",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=12,
                    ),
                ),
                (
                    "total_premium_due",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=12, null=True
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("M", "Monthly"),
                            ("Q", "Quarterly"),
                            ("H", "Half-yearly"),
                            ("Y", "Yearly"),
                        ],
                        db_index=True,
                        default="M",
                        max_length=1,
                    ),
                ),
                (
                    "cover",
                    models.PositiveIntegerField(
                        choices=[(500, "$500"), (1000, "$1000"), (2000, "$2000")]
                    ),
                ),
                (
                    "contract_premium",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=6, null=True
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="policies",
                        to="agents.agent",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="policies",
                        to="clients.client",
                    ),
                ),
                (
                    "paypoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="policies",
                        to="paypoints.paypoint",
                    ),
                ),
            ],
        ),
    ]
