# Generated by Django 5.2.7 on 2025-12-21 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0003_alter_policy_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="policy",
            name="city_address",
        ),
        migrations.RemoveField(
            model_name="policy",
            name="location_address",
        ),
        migrations.RemoveField(
            model_name="policy",
            name="street_address",
        ),
    ]
