# Generated by Django 5.2.7 on 2025-12-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0004_remove_policy_city_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="beneficiary_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="policy",
            name="beneficiary_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
