# Generated by Django 5.2.7 on 2025-12-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="premiumreceipt",
            name="receipt_number",
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
    ]
