# Generated by Django 5.2.7 on 2025-12-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0002_alter_premiumreceipt_receipt_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="premiumreceipt",
            name="receipt_number",
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
