# Generated by Django 5.2.7 on 2025-12-29 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("policies", "0004_remove_policy_city_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "billing_month",
                    models.DateField(help_text="Billing month (1st day of month)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="billings",
                        to="policies.policy",
                    ),
                ),
            ],
            options={
                "ordering": ["policy__contract_id"],
                "unique_together": {("policy", "billing_month")},
            },
        ),
    ]
