# Generated by Django 5.2.7 on 2025-12-18 15:25

import django.core.validators
import paypoints.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paypoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paypoint_code",
                    models.CharField(
                        db_index=True,
                        help_text="must start with pps",
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Paypoint code must start with 'pps' followed by lowercase letters only.",
                                regex="^pps[a-z]*$",
                            )
                        ],
                    ),
                ),
                ("paypoint_name", models.CharField(max_length=200)),
                (
                    "date_joined",
                    models.DateField(
                        validators=[paypoints.validators.validate_date_paypoint]
                    ),
                ),
            ],
        ),
    ]
