# Generated by Django 5.2.7 on 2025-12-29 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("policies", "0004_remove_policy_city_address_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CancellationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "effective_date",
                    models.DateField(
                        help_text="Date when cancellation becomes effective", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="REQUESTED",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_cancellations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policy",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cancellation_request",
                        to="policies.policy",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cancellation_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PendingCancellationApproval",
            fields=[],
            options={
                "verbose_name": "Pending Cancellation Approval",
                "verbose_name_plural": "Pending Cancellation Approvals",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("cancellations.cancellationrequest",),
        ),
        migrations.CreateModel(
            name="PendingCancellationRequest",
            fields=[],
            options={
                "verbose_name": "Pending Cancellation Request",
                "verbose_name_plural": "Pending Cancellation Requests",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("cancellations.cancellationrequest",),
        ),
    ]
