# Generated by Django 5.2.7 on 2025-12-18 15:25

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("policies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PremiumReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receipt_number", models.CharField(max_length=8, unique=True)),
                (
                    "amount_received",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                (
                    "date_received",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "total_received",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=10,
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="policies.policy",
                    ),
                ),
            ],
        ),
    ]
