# Generated by Django 5.2.7 on 2025-12-31 18:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0002_remove_administrator_user_id_administrator_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administrator",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
