# Generated by Django 5.2.7 on 2025-12-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Administrator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("user_id", models.CharField(max_length=5, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=30)),
                ("dob", models.TextField()),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_photos/"
                    ),
                ),
                ("date_created", models.DateField()),
                ("last_login", models.DateTimeField()),
                ("is_active", models.BooleanField()),
                ("is_superuser", models.BooleanField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
