# Generated by Django 5.2.7 on 2025-12-18 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_code",
                    models.CharField(
                        db_index=True, editable=False, max_length=10, unique=True
                    ),
                ),
                ("client_name", models.CharField(max_length=200)),
                ("client_surname", models.CharField(max_length=200)),
                (
                    "id_number",
                    models.CharField(
                        max_length=12,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="ID number must be in the format: NN-NNNNNN(L)NN or NN-NNNNNNN(L)NN (e.g. 43-123678K76)",
                                regex="^\\d{2}-\\d{6,7}[A-Za-z]\\d{2}$",
                            )
                        ],
                    ),
                ),
                ("dob", models.DateField()),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be 7–15 digits and may start with +",
                                regex="^\\+?\\d{7,15}$",
                            )
                        ],
                    ),
                ),
            ],
        ),
    ]
