# Generated by Django 5.2.7 on 2025-12-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="city_address",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="location_address",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="street_address",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
