# Generated by Django 5.2.7 on 2025-12-29 13:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agents", "0002_upload"),
        ("policies", "0004_remove_policy_city_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommissionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commission_month",
                    models.DateField(
                        help_text="Use the 1st day of the commission month"
                    ),
                ),
                (
                    "commission_due",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commission_rows",
                        to="agents.agent",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commission_rows",
                        to="policies.policy",
                    ),
                ),
            ],
            options={
                "ordering": ["policy__contract_id"],
                "unique_together": {("policy", "commission_month")},
            },
        ),
    ]
